### ISSUE TITLE
Rework columns filtering and search bar (with submenu)

### ISSUE THREAD

**Issue by fraxken** [dashlog/web-ui#11]
Current columns filtering and search bar could be improved by lookin at how npm deal with it on their statusboard: https://npm.github.io/statusboard/

![image](https://user-images.githubusercontent.com/4438263/230774209-55fc204c-be51-45cb-a27d-11409a5258e6.png)

This new design would allow to improve with new options in the future.

Current design is not great (it take a lot of space and doesn't scale well the more we add new columns keys).

**Comment by zwOk9** [comment]
I take the issue :D

**Comment by fraxken** [comment]
@zwOk9 are you working it?

**Comment by zwOk9** [comment]
yes I'm back this week  sorry

**Comment by PierreDemailly** [comment]
Fixed in #21
