### ISSUE TITLE
Ajout d'une sauvegarde des colonnes avec le localStorage

### ISSUE THREAD

**Issue by fraxken** [dashlog/web-ui#2]
Le statusboard permet de choisir les colonnes à afficher ce qui est plutôt pratique pour simplement travailler avec les colonnes qui nous sont les plus utiles. 

![image](https://user-images.githubusercontent.com/4438263/104025075-61babd00-51c4-11eb-8255-18fa50572c6c.png)

Néanmoins elles sont réinitialisées au rechargement de la page ce qui est dommage en matière d'expérience utilisateur. Il faudrait probablement sauvegarder la configuration des colonnes dans le local storage pour les recharger.

**Comment by abbesAlexandre** [comment]
hey thomas I take this issue.
