### ISSUE TITLE
Add logging with Pino.js

### ISSUE THREAD

**Issue by fraxken** [dashlog/web-ui#23]
Hello 👋 

As it stands, we have virtually no logs. In a lot of situations when we catch we do nothing (which is sometimes not a very good practice).

Would be cool to get a lot of more logs about what's going on the back-end (so if something goes wrong we have an idea where to look at).

**Comment by iasadk** [comment]
Hi, quick question. Do you want to store these logs too ?? or do you want to display them on the console?
I would like to work on this issue. Can you assign this to me ?

**Comment by fraxken** [comment]
Hi @iasadk 

My first goal was to add them to console. But anyway later we can output them easily in files since pino also support that (but I think that's not required right now).

**Comment by iasadk** [comment]
Ok @fraxken 
I will just log them to the console :)

**Comment by iasadk** [comment]
Hi @fraxken 
Is this how I'm supposed to add a logger to each try...catch or some other way. Sorry to disturb you like this as I'm new to Open source, so I'm asking you these silly questions. I hope you understand.
![image](https://github.com/dashlog/web-ui/assets/89456039/95133c36-2ed6-4836-b6a5-f882c0f71189)

**Comment by fraxken** [comment]
Hey @iasadk, no problem ^^

I guess it could depend, but it doesn't look bad. Do not hesitate to work on it and then open a Draft pull-request so we will help and review.

**Comment by abbesAlexandre** [comment]
I'm on it
