### ISSUE TITLE
Improve WebSocket implementation with a proper class

### ISSUE THREAD

**Issue by fraxken** [dashlog/web-ui#29]
Current WebSocket server implementation is directly embedded in [the root index.js file: https://github.com/dashlog/web-ui/blob/master/index.js#L35](https://github.com/dashlog/web-ui/blob/master/index.js#L35)

We can probably improve the maintability of the code by creating a class that will properly handle:
- connection event
- message event/handler (for each connection socket).

Using class could also avoid some repetition of code and having clear method name (mostly for the message).

No behavioral modification is expected, should work exactly the same (we will have improve the logics of the code itself later).

**Comment by Vinitvh** [comment]
Hi @fraxken, I would like to work on this issue.

**Comment by fraxken** [comment]
Hello @Vinitvh, no problem you can do it :)

**Comment by MaximeMRF** [comment]
Hello @fraxken, could you assign me this issue ?
