### ISSUE TITLE
Maintained badge is down

### ISSUE THREAD

**Issue by PierreDemailly** [dashlog/web-ui#30]
Maintained badge redirect to 404.
[![Maintenance](https://img.shields.io/badge/Maintained%3F-yes-green.svg?style=for-the-badge)](https://github.com/dashlog/web-ui/commit-activity)
It should redirect to https://github.com/dashlog/web-ui/graphs/commit-activity instead of https://github.com/dashlog/web-ui/commit-activity

**Comment by aishwarya-mali** [comment]
@PierreDemailly I can work on this issue.
